default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: deskapp_development

test:
  <<: *default
  database: deskapp_test

production:
  <<: *default
  database: deskapp_production
