# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bad0369dfbbf631b6456570c36b4ebbdcd4e06db5d819182b08f7b82c791a8c838e1f38b9ee519e7f42e9ac0e1fcbf65754485aa5da2c080740ba6660a921d8

test:
  secret_key_base: a5b38480ad416d16e2671a716ac03ecbedc26b8b253c3584675616b1a9f49021795978103bf8d2f91558a82afca6d3a4cf5366ec6dec1979abd2b74bd377ddb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
